---
deployment:
  tasks:
    - export DEPLOYPATH=/home/oxekim7dpn5n/public_html/
    - /bin/cp -R applications $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp -R test $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp -R admin.php $DEPLOYPATH
    - /bin/cp -R index.php $DEPLOYPATH
